name: Update docker base image

## Update the base image every day
on:
  push:
  workflow_dispatch:
  schedule:
  ## In UTC
  - cron: '0 0 * * *'

## Build base images to be used by other github workflows
jobs:

  build:
    name: Update base Erlang/OTP build images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - [ubuntu20.04, "linux/amd64,linux/arm64"]
          - [ubuntu18.04, "linux/amd64,linux/arm64"]
          - [ubuntu16.04, "linux/amd64,linux/arm64"]
          - [debian10   , "linux/amd64,linux/arm64"]
          - [debian9    , "linux/amd64,linux/arm64"]
          - [centos8    , "linux/amd64,linux/arm64"]
          - [centos7    , "linux/amd64,linux/arm64"]
          - [centos6    , "linux/amd64"]
          - [opensuse   , "linux/amd64,linux/arm64"]
          - [raspbian10 , "linux/arm64"]
          - [raspbian9  , "linux/arm64"]
          - [alpine3.14 , "linux/amd64,linux/arm64,linux/arm/v7"]

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          no-cache: true
          platforms: ${{ matrix.platform[1] }}
          tags: ghcr.io/rory-z/otp/base:${{ matrix.platform[0] }}
          file: .github/dockerfiles/Dockerfile.${{ matrix.platform[0] }}
